### ISSUE TITLE
Instructions on how to do GET

### ISSUE THREAD

**Issue by Jenni32222** [SoTrxII/Pandora-cooking-server#3]
Hi I am just starting out and was looking for instructions on where to do the GET command etc

**Comment by SoTrxII** [comment]
Hi,
So the *GET* is referring to the HTTP GET method. The cooking server is exposing an Web Server (on port 3004). You can query this web server using any web browser or client. 
For example, running:
> docker run -p 3004:3004 -it docker.pkg.github.com/sotrx/pandora-cooking-server/pandora-cooking-server:latest

And then in a browser : 
> http://localhost:3004/1?format=aac

Will process the first recording in aac, mixing all the player's audio together !

**Comment by Jenni32222** [comment]
Hi, thank you for the reply!

Is it correct that in this case Firefox tells me that I am unable to connect? Does it download directly in my browser or is it stored locally.

**Comment by SoTrxII** [comment]
Did you record something already ? If should prompt you to save the file.
